---
- include: centos.yml
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 6

- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Add configuration
  template: src={{ mysql_conf_tpl }} dest={{ mysql_conf_dir[ansible_distribution] }}/{{ mysql_conf_file }} owner=root group=root mode=0644
  when: mysql_conf_tpl != 'change_me'
  notify: restart mysql

- name: Start and enable service
  service: name=mysql state=started enabled=yes

- include: mysql_secure_installation.yml
  debug: var=mysql_secure_installation
  when: mysql_secure_installation and mysql_root_password is defined
