---
  - name: Install MySQLdb in global env
    pip: name=mysql-python version=1.2.5
    become: yes
    become_user: root

  - name: Set root Password for Ubuntu
    mysql_user:
      name: root
      host: localhost
      password: '{{ mysql_root_password }}'
      state: present
    become: yes
    become_user: root
    when: ansible_distribution == 'Ubuntu'

  - name: Set root Password
    command: mysqladmin -u root password {{ mysql_root_password }}
    become: yes
    become_user: root
    when: mysql_root_password is defined and ansible_distribution != 'Ubuntu'

  - name: Add configuration
    template: src={{ mysql_config_template }} dest={{ mysql_conf_dir }}/frappe.cnf owner=root mode=0644
    become: yes
    become_user: root

  - name: restart mysql linux
    service: name=mysql state=restarted
    become: yes
    become_user: root
    when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'

  # - name: Set root password on CentOS
  #   command: mysqladmin -u root password '{{ mysql_root_password }}'
  #   become: yes
  #   become_user: root
  #   when: mysql_root_password is defined and ansible_distribution == 'CentOS'

  - name: add launchagents folder mac
    file: path=~/Library/LaunchAgents state=directory
    when: ansible_distribution == 'MacOSX'

  - name: add mysql to mac startup
    file: src=/usr/local/opt/mariadb/homebrew.mxcl.mariadb.plist path=~/Library/LaunchAgents/homebrew.mxcl.mariadb.plist state=link force=yes
    when: ansible_distribution == 'MacOSX'

  - name: stop mysql mac
    command: launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.mariadb.plist
    when: ansible_distribution == 'MacOSX'

  - name: start mysql mac
    command: launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mariadb.plist
    when: ansible_distribution == 'MacOSX'
