---
  - name: download wkthmltox linux
    get_url: url=http://download.gna.org/wkhtmltopdf/0.12/0.12.3/wkhtmltox-0.12.3_linux-generic-{{ "amd64" if ansible_architecture == "x86_64" else "i386"}}.tar.xz dest=/tmp/wkhtmltox.tar.xz

  - name: Creates directory
    file: path=/tmp/wkhtmltox state=directory

  - name: unarchive wkhtmltopdf
    unarchive: src=/tmp/wkhtmltox.tar.xz dest=/tmp

  - name: copy to /usr/local/bin
    copy: source="/tmp/wkhtmltox/bin/wkhtmltopdf" dest="/usr/local/bin/wkhtmltopdf"