---
  - name: Check if ERPNext App exists
    stat: path="{{ bench_path }}/apps/erpnext"
    register: app

  - name: Get the ERPNext app
    command: bench get-app erpnext https://github.com/frappe/erpnext --branch {{ branch }}
    args:
      creates: "{{ bench_path }}/apps/erpnext"
      chdir: "{{ bench_path }}"
    when: not app.stat.exists

  - name: Check whether a site called site1.local exists
    stat: path="{{ bench_path }}/sites/site1.local"
    register: site_folder

  - name: Create a new site
    command: bench new-site site1.local --admin-password {{ admin_password }} --mariadb-root-password {{ mysql_root_password }}
    args:
      chdir: "{{ bench_path }}"
    when: not site_folder.stat.exists

  - name: Install ERPNext to default site
    command: bench --site site1.local install-app erpnext
    args:
      chdir: "{{ bench_path }}"
...