---
- hosts: localhost

- include: ../prerequisites/install_prerequisites.yml

- include: ../prerequisites/install_roles.yml

- include: macosx.yml
  when: ansible_distribution == 'MacOSX'

- name: setup bench and dev environment
  hosts: localhost
  vars:
    bench_repo_path: "/home/{{ ansible_user_id }}/.bench"
    bench_path: "/home/{{ ansible_user_id }}/{{ bench_name }}"
  tasks:
  # setup frappe-bench
  - include: includes/setup_bench.yml
    when: not run_travis and not without_bench_setup

  # setup development environment
  - include: includes/setup_dev_env.yml
    when: not run_travis and not production
