---
- hosts: localhost
  vars:
    bench_repo_path: "/home/{{ ansible_user_id }}/.bench"
    bench_path: "/home/{{ ansible_user_id }}/frappe-bench"
    mysql_config_template: "templates/simple_mariadb_config.cnf"
    mysql_conf_dir: /etc/mysql/conf.d/

  tasks:

  # install pre-requisites
  - name: install prequisites
    apt: pkg={{ item }} state=present
    with_items:
      # basic installs
      - build-essential
      - redis-server

      # for mariadb
      - software-properties-common

      # for wkhtmltopdf
      - libxrender1
      - libxext6
      - xfonts-75dpi
      - xfonts-base

      # for Pillow
      - libjpeg8-dev
      - zlib1g-dev
      - libfreetype6-dev
      - liblcms2-dev
      - libwebp-dev
      - python-tk

      # Ensure apt-transport-https
      - apt-transport-https

      # Python LDAP
      - libsasl2-dev
      - libldap2-dev
      
    become: yes
    become_user: root

  - name: install pillow prerequisites for Ubuntu < 14.04
    apt: pkg={{ item }} state=present
    with_items:
      - libtiff4-dev
      - tcl8.5-dev
      - tk8.5-dev
    when: ansible_distribution_version | version_compare('14.04', 'lt')
    become: yes
    become_user: root

  - name: install pillow prerequisites for Ubuntu >= 14.04
    apt: pkg={{ item }} state=present
    with_items:
      - libtiff5-dev
      - tcl8.6-dev
      - tk8.6-dev
    when: ansible_distribution_version | version_compare('14.04', 'ge')
    become: yes
    become_user: root

  - name: Add apt key for node repo
    apt_key:
      url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
      id: "68576280"
      state: present
    become: yes
    become_user: root

  - name: Add repo
    apt_repository:
      repo: "deb [arch=amd64,i386] https://deb.nodesource.com/node_6.x {{ ansible_distribution_release }} main"
      state: present
    register: node_repo
    become: yes
    become_user: root

  - name: Install nodejs 6.x
    apt:
      name: nodejs
      state: present
      update_cache: yes
      force: yes
    become: yes
    become_user: root

  # install MariaDB
  - include: includes/mariadb_ubuntu.yml

  # install WKHTMLtoPDF
  - include: includes/wkhtmltopdf.yml

  # setup MariaDB
  - include: includes/setup_mariadb.yml

  - debug:
      var: run_travis

  # setup frappe-bench
  - include: includes/setup_bench.yml
    when: not without_bench_setup and not run_travis

  # setup development environment
  - include: includes/setup_dev_env.yml
    when: not production and not run_travis and not without_bench_setup
