---

     - name: "Install packages list for CentOS 7"
       yum: pkg={{ item }} state=installed
       with_items:
            - git
            - mariadb-server
            - mariadb-devel
            - python-setuptools
            - nginx
            - zlib-devel
            - bzip2-devel
            - openssl-devel
            - postfix
            - python-devel
            - libxml2
            - libxml2-devel
            - libxslt
            - libxslt-devel
            - redis
            - libXrender
            - libXext
            - supervisor
            - cronie
            - sudo
            - which
            - xorg-x11-fonts-75dpi
            - xorg-x11-fonts-Type1
            - nodejs
            - npm
            - libtiff-devel
            - libjpeg-devel
            - libzip-devel
            - freetype-devel
            - lcms2-devel
            - libwebp-devel
            - tcl-devel
            - tk-devel
